# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
path_classifiers:
  test:
    - "*/fuzz_test/**/*"
    - "*/test/**/*"
extraction:
  cpp:
    prepare:
      packages:
        - clang-12
        - clang++-12
        - ccache
      script:
        - mkdir ~/.conan
        - cat /usr/local/share/ca-certificates/semmle-cache-ca/semmle-cache-ca.crt >> ~/.conan/cacert.pem
        - python3 -m pip install --upgrade pip setuptools
        - python3 -m pip install conan
        - python3 -m pip install cmake
        - source ~/.profile
    configure:
      command:
        - mkdir build
        - CC=clang-12 CXX=clang++-12 cmake -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build
    index:
      build_command: CC=clang-12 CXX=clang++-12 cmake --build ./build -- -j2
